// <auto-generated />
namespace OnlineShop.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Initdatabase : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Initdatabase));
        
        string IMigrationMetadata.Id
        {
            get { return "201902280339266_Init-database"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
